version: 0.2

phases:
  install:
    commands:
      - echo Installing app dependencies...
      - yarn install

  build:
    commands:
      - echo Building Site...
      - yarn build
artifacts:
    files:
        - '**/*'